### PR TITLE
fix-bug:fixing the validations of the incidents form

### LINKED ISSUE #184: The "Reason" field in the incidents UI lacks a character length limit for user input
**Describe the bug**
The incidents UI includes a "Reason" section where users can provide details about the incident. However, the text field does not have a character length limit, which can be problematic when saving this information in the database. Additionally, users are unable to see the length of their input text.

**To Reproduce**
1. Launch the Hermes application.
2. Tap on any street on the map.
3. In the waypoint options, press the incidents button.
4. In the incidents UI, navigate to the "Reason" field.
5. Enter some text to verify if the text field has a length limit.

**Expected behavior**
The text field should enforce a length limit and provide feedback to the user about the limit.

**Screenshots**
Bug of resaon field

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android
 - Version: 13

**Additional context**
It would be helpful to display the length limit at the top of the text field, using the syntax "0/30" (increasing the number as the user types). This would provide users with real-time feedback on their input and ensure compliance with the desired character limit.

### PR DESCRIPTION
**Pull request by victor0villca**
**Author**
 Victor Villca @victor0villca 
**Bug Fix Description**
This is the bug fix of the following bug: https://github.com/CampusDelSaber/hermes/issues/184#issue-1781574446
**Taiga**
https://tree.taiga.io/project/marcel-morales-hermes/issue/504
**Extra**
This bug fix also resolves the following validation scenarios:
- Validation for an empty text field.
- Validation for a text field with only spaces.

**Reviewers**
- @daniel-espinoza-79 
- @CatCoder36 
- @JuanPabloArequipa

### CODE REVIEW

**Review by CatCoder36 — APPROVED** [review]
Good job

**Comment by JuanPabloArequipa** [comment]
This fix works. But I have a suggestion:
You are performing the validation when the accept button is pressed, after the user has entered text without any character limits. It would be more understandable to allow the user to see the character count while they are typing(0/25 and increase the zero when user writes). Once the limit is reached (25/25), the text field shouldn't insert more characters typed.

**Review by daniel-espinoza-79 — APPROVED** [review]
The validation of the limit of allowed characters was done correctly.

**Comment by victor0villca** [comment]
The bug reported is already fixed.

> This fix works. But I have a suggestion:
> You are performing the validation when the accept button is pressed, after the user has entered text without any character limits. It would be more understandable to allow the user to see the character count while they are typing(0/25 and increase the zero when user writes). Once the limit is reached (25/25), the text field shouldn't insert more characters typed.
The bug reported is already fixed.

**Review by JuanPabloArequipa — APPROVED** [review]

**Pull request merged**
