### PR TITLE
Developers want to have a CI/CD workflow

### PR DESCRIPTION
**Pull request by zrock-dev**
### What did I do?
Created a CI/CD workflow for the develop branch for the following stages:
- Build – Executed on push, and pull request to develop
- Test – Executed on push, and pull request to develop
- Code Analysis: Executed on push to develop.
- APK distribution: Executed on push to develop

### How did I do it?
- By implementing a YML script for the GitHub actions.
- By updating the app/build.gradle to sign APK's
- By updating the build.gradle to use Gradle Scan and publish a scan for every failed gradle job related.

### Why did I do it?
So that we as developers can have our develop branch in a more stable fashion.

### Code Review 
@santiCaballeroM  
@CatCoder36  
@VillalobosGarciaGaby  

### Tester 
@santiCaballeroM  
@CatCoder36  
@VillalobosGarciaGaby  

### Trainer 
@mmoralesv

### CODE REVIEW

**Comment by zrock-dev** [comment]
US - https://tree.taiga.io/project/marcel-morales-hermes/us/428

**Comment by santiCaballeroM** [comment]
Built Correctly :heavy_check_mark:

**Review by santiCaballeroM — APPROVED** [review]
Built Correctly :heavy_check_mark:

**Review by CatCoder36 — APPROVED** [review]

**Review by santiCaballeroM — APPROVED** [review]

**Review by VillalobosGarciaGaby — APPROVED** [review]

**Comment by VillalobosGarciaGaby** [comment]
good job

**Pull request merged**
