### PR TITLE
bug-fix:fixing the bug reset default when incident cancelled

### LINKED ISSUE #200: The "Reason" field in the incidents UI does not clear its content after closing and re-opening UI
**Describe the bug**
The incidents UI includes a "Reason" section where users can provide details about the incident. The text field does not reset its content when user interacts with incidents UI many times at different waypoints.

**To Reproduce**
1. Launch the Hermes application.
2. Tap on any street on the map.
3. In the waypoint options, press the incidents button.
4. In the incidents UI, fill the "Reason" field with any text.
5. Press on Accept or Cancel button.
6. Tap on another street on the map.
7. In the incidents UI at Reason field, the input text inserted before will persist.

**Expected behavior**
The text field should be cleared every time the incidents UI is displayed.

**Screenshots**
Bug of reseting reason field 1
Bug of reseting reason field 2

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android
 - Version: 13

**Additional context**
When user open several incidents UIs, the Reason field shouldn't have any content to let user start writing the new incident's info.

### LINKED ISSUE #215: Information not reset to default correctly when the incident is cancelled.
**Describe the bug**
When trying to generate a new incident in the map of our application and after filling in all the incident data, if the cancel button is pressed, the incidents window closes successfully. However, when trying to generate a new incident, the data from the previous incident is not deleted and continues to appear in the respective fields. The expected behavior would be for the fields to be empty, like the first time the report incidents function is entered.

**To Reproduce**
**1.** Open the Hermes app.
**2.** Log in with the defined Hermes account.
**3.** The map will be displayed, click anywhere on the map making sure to click on a street.
**4.** Once clicked, a kind of new small window will appear at the bottom of the screen, in the "Report" options section you will find the "Incident" button visible.
**5.** Press or click the "Incident" button, the current window will close and another window called "Incident Report" will be displayed.
**6.** Once you enter that window, fill in the details of the incident and then press the "Cancel" button. The window will close successfully.
**7.** Repeat steps 3 to 5. When you open the "Incident Report" window, you will notice that the data from the previous incident was not deleted.

**Expected behavior**
After canceling the creation of an incident, if you try to generate a new incident, all the fields for the incident data should be empty, just like the first time you access the report incident function.

**Screenshots**
**Before to press the button cancel:**
image

**After create a new incident again:**
image

**Smartphone**
- Device: Pixel 3a API 30
- OS: Android
- Version 11

### PR DESCRIPTION
**Pull request by victor0villca**
**Author**
 Victor Villca @victor0villca 
**Bug Fix Description**
This is the bug fix of the following bug: https://github.com/CampusDelSaber/hermes/issues/215#issue-1781643678
It also fixes another  very similar bug: https://github.com/CampusDelSaber/hermes/issues/200#issue-1781611773
**Taiga**
https://tree.taiga.io/project/marcel-morales-hermes/issue/510
**Extra**
This bug-fix also resolves a keyboard bug described in the comments of this pull request.

### CODE REVIEW

**Comment by JuanPabloArequipa** [comment]
There is another bug.
After writing at Reason field and pressing cancel or accept button, the keyboard is not being closed and it is possible to continue writing at Reason field whether it is not displayed.

Expected: After pressing on cancel or accept, the keyboard should disappear and user shouldn't be able to continue editing.

Attachment:
https://github.com/CampusDelSaber/hermes/assets/135129192/8fb78baa-c09a-4354-80d9-0e2609c55bc7

**Comment by victor0villca** [comment]
@JuanPabloArequipa 
This bug will also be resolved in this pull request.

> There is another bug. After writing at Reason field and pressing cancel or accept button, the keyboard is not being closed and it is possible to continue writing at Reason field whether it is not displayed.
> 
> Expected: After pressing on cancel or accept, the keyboard should disappear and user shouldn't be able to continue editing.
> 
> Attachment: https://github.com/CampusDelSaber/hermes/assets/135129192/8fb78baa-c09a-4354-80d9-0e2609c55bc7

**Review by Misax148 — APPROVED** [review]
Good job!

**Comment by victor0villca** [comment]
This bug-fix is also fixing the next bug: https://github.com/CampusDelSaber/hermes/issues/200#issue-1781611773

**Review by JuanPabloArequipa — APPROVED** [review]

**Review by JCarlosHidalgoSosa — APPROVED** [review]
gj

**Pull request merged**
