### PR TITLE
Bug/ID-534/The UserInformation section cannot be accessed due to problems with email validation when you are Admin user

### LINKED ISSUE #282: Bug/ID-534/The UserInformation section cannot be accessed due to problems with email validation after you registered like Admin user
### Severity: Hight

**Linked Test Case Failed:**  https://app.testlodge.com/a/37307/projects/55109/suites/229241?expand_section=404319#case_4016032

**Description:**
After the user logs in with their Google account as an admin user and tries to access the section to view or edit their data, the Hermes application unexpectedly closes. Launching registrations that are linked to the persistence of the code to be an administrator user, as it becomes null and is called again.

**Steps to reproduce:**

1. Open the Hermes application. A screen will appear with a button that says "Sign up with Google".
2. Click on the "Sign up with Google" button. A window will appear with the Google accounts you have stored on your mobile.
3. Select the Google account you have not signed up with before. Once selected, a window will appear showing your data and a combobox with a hint that says 'TypeUser'.
4. In this window click on the combobox and select the user type 'Administrator'. The combobox should change the text it displays to the user type you clicked previously.
5. Click on the button with the text 'Sign Up'. You should be prompted for a verification code.
6. A verification code will be sent to you when your application has been approved. Wait and check your email until you receive the code.
7. Once you receive the code, enter it in the text fields.
8. Click the button with the text 'Verify Account'. You should see a screen with a map.
9. In the tab that appears, press the button with the sandwich icon in the upper left corner. A menu with different options will be displayed.
10. In the menu click on the "User account" option. Immediately the application closes and the logs related to the validation of the Administrator user code are generated.

**Expected result:**
Upon clicking the "User account" option, the application should navigate to the UserInformation section, allowing the Administrator user to view or edit their data. No unexpected crashes or application closures should occur.

**Current result:**
After selecting the "User account" option, the Hermes application abruptly closes without any indication of an error or warning message, and logs are generated indicating issues with the validation of the Administrator user code.

**Additional Information:**
* Reproducibility: This issue is reproducible consistently by following the steps mentioned above.

**Attachments:**

Result:

image

image

Linked Logs:

image

### PR DESCRIPTION
**Pull request by JeferssonCL**

### CODE REVIEW

**Review by Karvlox — DISMISSED** [review]
I don't any comments.

**Review by Karvlox — APPROVED** [review]

**Comment by VillalobosGarciaGaby** [comment]
image
 does not change your combo box.

**Comment by JeferssonCL** [comment]
@VillalobosGarciaGaby Te observations were solved.

**Review by VillalobosGarciaGaby — APPROVED** [review]

**Review by saletG08 — APPROVED** [review]
I don't have any comments

**Pull request merged**
