### PR TITLE
Bug Fix/ ID-506 & ID-509/ Incorrect format of username and full name text fields in account information

### LINKED ISSUE #209: Incorrect Format of the full name field in Account Information
**Description**
When I try to edit my account information in the "User Account" section, when editing the "Full Name" field, I can use numbers and line breaks, and letters with accents are not displayed.

**To Reproduce**
1. Open the Hermes application.
2. Login if you are not logged in.
3. Click on the hamburger button on the upper left side to open the menu.
4. Click on the "Account" option from the menu.
5. Click on "Edit information" button.
6. Click on "Full name" text field.
7. Write numbers, line breaks and letters with accents.
8. Click on "Save Information" button.

**Expected behavior**
The text field should only accept letters, and letters with accents should be displayed.

**Screenshots**
image
  
image

**Smartphone:**
 - Device: Samsung A52
 - OS: Android 13

**Other bugs**
[Similar Bug](https://github.com/CampusDelSaber/hermes/issues/209)

### LINKED ISSUE #213: Incorrect Format of Username Text Field in Account Information
**Description**
When I try to edit my account information in the "User Account" section, when editing the "Username" field, I can use line breaks, and letters with accents are not displayed.

**To Reproduce**
1. Open the Hermes application.
2. Login if you are not logged in.
3. Click on the hamburger button on the upper left side to open the menu.
4. Click on the "Account" option from the menu.
5. Click on "Edit information" button.
6. Click on "Username" text field.
7. Write line breaks and letters with accents.
8. Click on "Save Information" button.

**Expected behavior**
The text field should only accept letters, and letters with accents should be displayed.

**Screenshots**
image  
image

**Smartphone:**
 - Device: Samsung A52
 - OS: Android 13

### PR DESCRIPTION
**Pull request by JeferssonCL**
## Author
@JeferssonCL 

## What?
The bugs linked to the account information text fields were corrected.

## How?
Implement something like regex for the accepted characters and adding an attribute to not perform the line break.

## Why?

- To disallow unaccepted input types.
- To avoid having line breaks that ruin the ui.
- To have a more maintainable app.

## Code Reviewers
@daniel-espinoza-79 
@aguirrekarina 
@JCarlosHidalgoSosa  

## Trainer 
@mmoralesv 

**Linked Bug Reports:**
-  https://github.com/CampusDelSaber/hermes/issues/213
- https://github.com/CampusDelSaber/hermes/issues/209

### CODE REVIEW

**Review by daniel-espinoza-79 — APPROVED** [review]
The text field bug has been fixed correctly.

**Comment by aguirrekarina** [comment]
I can put blanks in the user name.

image

**Comment by JeferssonCL** [comment]
Observations were resolved @aguirrekarina

**Review by aguirrekarina — APPROVED** [review]

**Review by JCarlosHidalgoSosa — APPROVED** [review]
Good job

**Comment by JeferssonCL** [comment]
### Solucion de los Bugs:

Selection_091
Selection_092

**Pull request merged**
