### PR TITLE
Task/id 373/enhance walkable bidirectional graph

### PR DESCRIPTION
**Pull request by victor0villca**
**Author:**
Victor Villca
@victor0villca 

**Description:**
Enhance of the existing graph structure by adding bidirectional connections for walkable transport routes.

**Task on Taiga:** https://tree.taiga.io/project/marcel-morales-hermes/task/373

### CODE REVIEW

**Comment by CatCoder36** [comment]
Verify that your feature branch is updated to develop, it is rare 62 changes for a task

**Review by mmoralesv — APPROVED** [review]

**Comment by JCarlosHidalgoSosa** [comment]
Resolve conflicts

**Review by CatCoder36 — APPROVED** [review]
Good job

**Review by JCarlosHidalgoSosa — APPROVED** [review]
good job

**Pull request merged**
