### PR TITLE
Feature/id 357/two points naviagtion options

### PR DESCRIPTION
**Pull request by santiCaballeroM**
## Authors: 
- Santiago Caballero Manzaneda @santiCaballeroM 

### **What?**
- Navigation Options functionality/Ui classes and methods. :heavy_check_mark: 
- Navigation Transportation Options Ui implementation, enum class of each type :heavy_check_mark:

### **How?**

- Following MVC creating controller classes and xml files methods modified.

### **Why?**
- In order to have the navigation options of current location or select the start point in the map, and update the ui components

### **Code reviewers/Testers**
@aguirrekarina 
@denisgandel 
@GastonGutierrezC 

### **Trainer (General Reviewer):**
@mmoralesv

### CODE REVIEW

**Comment by aguirrekarina** [comment]
the space where the arrival point is shown is cut off.
image

**Comment by aguirrekarina** [comment]
Each type of transport is repeated twice..

https://github.com/CampusDelSaber/hermes/assets/101665677/cc439a83-8964-4cdb-a25b-c412c61c228c

**Comment by aguirrekarina** [comment]
When I click on "Choose on map" to select another starting point, the waypoints are no longer marked, but the point is changed.

https://github.com/CampusDelSaber/hermes/assets/101665677/91330923-4188-47ac-8029-20363230093e

**Comment by santiCaballeroM** [comment]
Observations Fixed

**Review by GastonGutierrezC — APPROVED** [review]
I have no observations

**Review by mmoralesv — APPROVED** [review]

**Review by aguirrekarina — APPROVED** [review]

**Pull request merged**
