### PR TITLE
Bug/id 444/updating the role in the account information

### LINKED ISSUE #124: Unable to update user role in account information
### Severity: Hight

**Description:**
When running the application, the functionality of the account information, the user can change his role, at the time he does so, he does not get to see the verification screen of the code sent in his email.    
This bug affects the functionality of the account information.

**Steps to reproduce:**

1. Run the Hermes application.
2. If you already have an active session, continue with step 3. Otherwise, the Log in activity will appear. Log in with your Gmail account by clicking on the Log in button and you can choose the "General" role.
3. The application will open, showing the map of your city, click on the burger menu.
4. In the menu view, click on the "Account".
5. In the "Account" view you can edit your information, to an "Administrator" role.

**Expected result:**
When changing roles, the user will see the code verification window so that he/she can be "Administrator".

**Current result:**
The application currently does not show the code verification display, when the user tries to change their role in the account information.

**Attachments:**

image

### PR DESCRIPTION
**Pull request by VillalobosGarciaGaby**
Describe the bug

When running the application, the functionality of the account information, the user can change his role, at the time he does so, he does not get to see the verification screen of the code sent in his email.    
This bug affects the functionality of the account information.

To Reproduce

Run the Hermes application.
If you already have an active session, continue with step 3. Otherwise, the Log in activity will appear. Log in with your Gmail account by clicking on the Log in button and you can choose the "General" role.
The application will open, showing the map of your city, click on the burger menu.
In the menu view, click on the "Account".
In the "Account" view you can edit your information, to an "Administrator" role.

Expected behavior: 

Screenshot from 2023-06-28 18-31-35

Smartphone:

- Device:  Google Pixel 4      
- Android API 31     
- Android version 11 or higher

### CODE REVIEW

**Comment by JCarlosHidalgoSosa** [comment]
First of all, I delete my current account, then, I sign up as general user, I reproduced all steps mentioned but now, I'm not able to change from general user to administrator, the item isn't appears.

Screenshot_20230628_201328

**Review by JCarlosHidalgoSosa — APPROVED** [review]
Issue solved

**Review by jhael-arce-jalafund — CHANGES_REQUESTED** [review]
solve merge conflict

**Comment by denisgandel** [comment]
https://github.com/CampusDelSaber/hermes/assets/135136502/09396fee-5055-4717-a908-ad04bd244db1

When I go back to return to main, it does not let me and sends me to the verification code screen.

**Comment by JCarlosHidalgoSosa** [comment]
> WhatsApp.Video.2023-06-28.at.21.02.27.mp4 
> When I go back to return to main, it does not let me and sends me to the verification code screen.

I don't have this bug, go backward from edit account screen, app redirects me to map.

**Review by denisgandel — APPROVED** [review]

**Review by jhael-arce-jalafund — APPROVED** [review]

**Review by mmoralesv — APPROVED** [review]

**Pull request merged**
