### PR TITLE
ID-169[Feature] Map Creation

### PR DESCRIPTION
**Pull request by camilabustosvalverde**
## Authors: 
- Axel Ayala @Misax148
- Camila Bustos @camilabustosvalverde 

### **What?**
- Initial configuration, dependencies and gradle configuration to initialize the map creation. :heavy_check_mark: 
- Visualization and Rendering of map. :heavy_check_mark:

### **How?**

- Build gradles files, settings gradle and AndroidManifest.xml files modified.

- Creation of MapConfigure and Map Display, MainActivity class modification and his layout. 

### **Why?**
- Files' modifications and  MapConfigure and Map Display  creation  done for map's visualization.

### **Code reviewers/Testers**
@aguirrekarina 
@CatMauCoder 
@JeferssonCL 

### **Trainer (General Reviewer):**
@mmoralesv

### CODE REVIEW

**Comment by JeferssonCL** [comment]
Solve Merge conflicts

**Review by CatCoder36 — APPROVED** [review]
Without observations, the branch complies with functionality.

**Comment by Misax148** [comment]
> Solve Merge conflicts

Merge conflicts was fixed

**Review by mmoralesv — APPROVED** [review]

**Comment by JeferssonCL** [comment]
Without observations, the branch complies with functionality. Approved

**Review by JeferssonCL — APPROVED** [review]

**Pull request merged**
