### PR TITLE
Bugfix/us 512/issue with user role update in the data base

### LINKED ISSUE #226: Issue with User Role Update in the Data Base.
Describe the bug
When the user changes the role, his/her role in the database is not updated, but the account is duplicated and you get two accounts of the same user, where one has the role of GENERAL and the other has the role of ADMINISTRATOR.

To Reproduce

1. Go to the application
2. Sign up as a GENERAL user
3. Open the menu
4. Click in "Account" option
5. Click in "Edit information" button
6. Change the role to ADMINISTRATOR
7. Introduce your verification code
8. Repeat the step 3 and 4
9. See the error

Screenshots

image

Device: Realme C11 2021
OS: Android
Version 11

### PR DESCRIPTION
**Pull request by denisgandel**
Bugfix #226 

## AUTHORS:
@VillalobosGarciaGaby 
@denisgandel

### CODE REVIEW

**Review by JorgeHB69 — COMMENTED** [review]
When an admin user wants to edit his account and change his user type, the drop list only shows the same user type.

image

**Review by daniel-espinoza-79 — COMMENTED** [review]
When an administrator user clicks on "Edit Information" ->" Save Information"-> "I'm sure" , the verification code is sent again.
Screencast from 02-07-23 14_25_47

**Comment by VillalobosGarciaGaby** [comment]
@JorgeHB69 It is one of the requirements that When the user is an Administrator he can not change to a general user, but a general user can be an administrator user.

**Review by daniel-espinoza-79 — APPROVED** [review]

**Review by Misax148 — APPROVED** [review]

**Comment by JorgeHB69** [comment]
> @JorgeHB69 It is one of the requirements that When the user is an Administrator he can not change to a general user, but a general user can be an administrator user.

Yes, @VillalobosGarciaGaby. I understand that, but if the user can't change his role, the drop list shouldn't appear with any option to change.

**Review by JorgeHB69 — APPROVED** [review]
Everything is OK. You changed the drop list, good job.

**Pull request merged**
