### PR TITLE
ID - 253 and 259 | Logo app and color palette

### PR DESCRIPTION
**Pull request by denisgandel**
# LOGO AND COLOR PALETTE

## WHAT?

- Create the application logo.
- Create the color palette of the application.

## HOW?
- Investigating the psychology of colors.
- Making sketches and looking for different ideas.

## WHY?
To transmit confidence, security, and efficiency of our application, in addition to having a way for users to identify us.

## CODE REVIEWERS:

TEAM A: @aguirrekarina 
TEAM B: @JeferssonCL 
TEAM C: @GastonGutierrezC 

## TRAINER

@mmoralesv 

## WIKI

[LOGO AND COLOR PALETTE](https://tree.taiga.io/project/marcel-morales-hermes/wiki/logo-and-color-palette)

### CODE REVIEW

**Comment by denisgandel** [comment]
The previous Pull Request had problems to revert a commit, so to avoid problems when merging with the develop create a new commit branch with the updated changes from the develop.

**Comment by GastonGutierrezC** [comment]
the color palette and the logo were successfully realized.

**Review by GastonGutierrezC — APPROVED** [review]

**Review by JeferssonCL — APPROVED** [review]
No observations.

**Review by JeferssonCL — COMMENTED** [review]
There is an error I think is missing modules or dependencies: 
Screenshot from 2023-06-07 22-44-17

**Review by aguirrekarina — APPROVED** [review]

**Pull request merged**
