### PR TITLE
Feature/id 226/sign up implementation

### PR DESCRIPTION
**Pull request by daniel-espinoza-79**
Register user using third-party services (Implementation)
I did the implementation of signUp to register with google 

Things to consider for testing :
Having a mobile device with google place store services
Tester 
@JeferssonCL 
CodeReview
@SamuelEscalera

### CODE REVIEW

**Comment by SamuelEscalera** [comment]
- [x] Code readability and consistency
- [x] Structure and organization of the code
- [x] Documentation

**Approved**

**Review by SamuelEscalera — APPROVED** [review]

**Review by JeferssonCL — COMMENTED** [review]
Problems were found with the registration of Code Compilers as clients (OpenID) . Can't signUp

**Comment by JeferssonCL** [comment]
> * [x]  Code readability and consistency
> * [x]  Structure and organization of the code
> * [x]  Documentation
> 
> **Approved**

**Review by JeferssonCL — APPROVED** [review]
No observations.

**Pull request merged**
